### ISSUE TITLE
Running rxjs-5-to-6-migrate -p src/tsconfig.app.json fails

### ISSUE THREAD

**Issue by Blair2004** [ReactiveX/rxjs-tslint#32] opened 2018-05-06 10:23 UTC
Hi, 
i've been trying to update to angular 6, but i'm failing while trying to run the rxjs migration. Actually on my Windows computer, the folder name of my user is "Blair Jersyer" with a space. When i'm running the code i get an error like so : 

`"C:\Users\Blair" is not a valid command`

I assume it's because there is a space on that folder. After having console.logged the command on `C:\Users\Blair Jersyer\AppData\Roaming\npm\node_modules\rxjs-tslint\rxjs-5-to-6-migrate.js:18` here is the resulting command : 

`C:\Users\Blair Jersyer\AppData\Roaming\npm\node_modules\rxjs-tslint\node_modules\.bin\tslint -c C:\Users\Blair Jersyer\AppData\Roaming\npm\node_modules\rxjs-tslint\rxjs-5-to-6-migrate.json -p src/tsconfig.app.json --fix`

Still wondering if the space within my username (Blair Jersyer) is the cause of this issue. 

Regards.

**Comment by mgechev** [comment] 2018-05-06 16:01
Yes it's a duplicate of https://github.com/ReactiveX/rxjs-tslint/issues/25.

**Closed by mgechev** 2018-05-06 16:01 UTC
